api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('api/cadastro/empresa', CadastroEmpresaApi.as_view())
]

autenticacao/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('ativar_conta/<str:token>/', views.ativar_conta, name="ativar_conta"),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastro_empresa/', views.cadastro_empresa, name='cadastro_empresa'),
    path('cadastro_aluno/', views.cadastro_aluno, name='cadastro_aluno'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
]

paginas/urls.py
from django.urls import path
from .views import PaginaInicial, Sobre

app_name = "pages"

urlpatterns = [
    # path('endereço/', MinhaView.as_view(), name='nome da url'),
    path('', PaginaInicial.as_view(), name='home'),
    path('sobre/', Sobre.as_view(), name='sobre'),
    ]

sintproedu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('autenticacao.urls')),
    path('', include ('paginas.urls')),
    path('', include ('core.urls')),
    path('', include ('api.urls')),
]

autenticacao/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class Estado(models.Model):
    estado = models.CharField(max_length=2, unique=True, null=True, verbose_name='estado')

    def __str__(self):
        return self.estado

class Cidade(models.Model):
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    cidade = models.CharField(max_length=30, null=True, verbose_name='cidade')

    def __str__(self):
        return self.cidade

class Bairro(models.Model):
    cidade = models.ForeignKey(Cidade, null=True, on_delete=models.CASCADE)
    bairro = models.CharField(max_length=30, null=True, unique=True, verbose_name='bairro')

    def __str__(self):
        return self.bairro

class Endereco(models.Model):
    bairro = models.ForeignKey(Bairro, null=True, on_delete=models.CASCADE)
    rua = models.CharField(max_length=200, null=True, unique=True, verbose_name='rua')
    cep = models.CharField(max_length= 9, null=True, unique=True, verbose_name='cep')

    def __str__(self):
        return self.cep

class Complemento(models.Model):
    endereco = models.ForeignKey(Endereco, null=True, on_delete=models.CASCADE)
    numero = models.CharField(max_length=5, null=True, verbose_name='numero')
    complemento = models.CharField(max_length=50, null=True, verbose_name='complemento')

    def __str__(self):
        return self.numero

class Universidades(models.Model):
    estado = models.ForeignKey(Estado, on_delete=models.DO_NOTHING)
    instituicao = models.CharField(max_length=100 ,null=True, unique=True, verbose_name='instituicao')

    def __str__(self):
        return self.instituicao

class Atuacao(models.Model):
    atuacao = models.CharField(max_length=5, null=True, unique=True, verbose_name='atuacao')

    def __str__(self):
        return self.atuacao


class Aluno(models.Model):
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE) 
    cpf = models.CharField(max_length=14, null=True, unique=True, blank=True, verbose_name='cpf')
    endereco = models.ForeignKey(Endereco, on_delete=models.SET_NULL, blank=True, null=True)
    instituicao = models.ForeignKey(Universidades, on_delete=models.SET_NULL, blank=True, null=True)
    atuacao = models.ForeignKey(Atuacao, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.usuario
    

class Empresa(models.Model):
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    cnpj = models.CharField(max_length=18, null=True, unique=True, verbose_name='cnpj')
    representante = models.CharField(max_length=50, null=True, verbose_name='representante')
    endereco = models.ForeignKey(Endereco, on_delete=models.SET_NULL, blank=True, null=True)
    atuacao = models.ForeignKey(Atuacao, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.usuario



class Ativacao(models.Model):
    token = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.user

autenticacao/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class UserForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    def clean_email(self):
        e = self.cleaned_data['email']
        if User.objects.filter(email=e).exists():
            raise ValidationError('O email {} já está cadastrado.'.format(e))
        return e

autenticacao/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .utils import password_is_valid, email_html, email_valido, email_username, cpf_valido, cnpj_valido
from django.shortcuts import redirect, get_object_or_404
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.messages import constants
from django.conf import settings
from .models import Ativacao, Atuacao, Empresa, Aluno, Estado , Cidade, Bairro, Endereco, Complemento, Universidades
from hashlib import sha256
import os
from django.contrib.auth.models import Group

def cadastro(request):

    request.method == "GET"
    if request.user.is_authenticated:
        return redirect('/')
    return render(request, 'cadastro.html')


def cadastro_empresa(request):

    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'cadastro_empresa.html')

    elif request.method == "POST":
        first_name = request.POST.get('nome')
        represent = request.POST.get('representante')
        cnpj = request.POST.get('cnpj')
        atuacao = request.POST.get('atuacao')
        cep = request.POST.get('cep')
        rua = request.POST.get('address')
        numero = request.POST.get('number')
        complemento = request.POST.get('complement')
        bairro = request.POST.get('neighborhood')
        cidade = request.POST.get('city')
        estado = request.POST.get('region')
        confirma_email = request.POST.get('confirma_email')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirmar_senha = request.POST.get('confirmar_senha')
        grupo = get_object_or_404(Group, name='GrupoEmpresa')
        
        if (len(first_name.strip()) == 0) or (len(represent.strip()) == 0) or (len(confirma_email.strip()) == 0) or\
                (len(email.strip()) == 0) or (len(senha.strip()) == 0) or (len(confirmar_senha.strip()) == 0):
            messages.add_message(request, constants.ERROR, 'Preencha todos os campos')
            return redirect('/cadastro_empresa')


        if not email_username(request, confirma_email, email):
            return redirect('/cadastro_empresa')

        if not password_is_valid(request, senha, confirmar_senha):
            return redirect('/cadastro_empresa')


        if not email_valido(request, email, User):
            return redirect('/cadastro_empresa')
        
        if not cnpj_valido(request, cnpj, Empresa):
            return redirect('/cadastro_empresa')

        try:
        
            try: estado = Estado.objects.get(estado=estado)

            except:
                estado = Estado(estado=estado)
                estado.save()

            try: cidade = Cidade.objects.get(cidade=cidade)
    
            except:
                cidade = Cidade(estado=estado, cidade=cidade)
                cidade.save()

            try: bairro = Bairro.objects.get(bairro=bairro)
                
            except:
                bairro = Bairro(cidade=cidade, bairro=bairro)
                bairro.save()

            try: cep = Endereco.objects.get(cep=cep)
            
            except:
                endereco = Endereco(bairro=bairro, rua=rua, cep=cep)
                endereco.save()

            try: complemento = Complemento.objects.get(complemento=complemento)
                
            except:
                complemento = Complemento(endereco = endereco, numero=numero, complemento=complemento)
                complemento.save()

            try: atuacao = Atuacao.objects.get(atuacao=atuacao)
            
            except:
                atuacao = Atuacao(atuacao = atuacao)
                atuacao.save()


            user = User.objects.create_user(username=confirma_email,
                                            first_name=first_name,
                                            email=email,
                                            password=senha,
                                            is_active=True)
            user.groups.add(grupo)
            user.save()

            empresa = Empresa(representante=represent,
                                cnpj=cnpj,
                                endereco=endereco,
                                atuacao=atuacao,
                                usuario=user)
            empresa.save()

            token = sha256(f'{first_name}{email}'.encode()).hexdigest()
            ativacao = Ativacao(token=token, user=user)
            ativacao.save()

            messages.add_message(request, constants.SUCCESS, 'Empresa cadastrada com SUCESSO! Faça LOGIN para continuar!')
            return redirect('login')

        except:
            messages.add_message(request, constants.ERROR, 'Erro interno no sistema!!!')
            return redirect('/cadastro_empresa')


def cadastro_aluno(request):

    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'cadastro_aluno.html')

    elif request.method == "POST":
        first_name = request.POST.get('nome')
        last_name = request.POST.get('sobrenome')
        username = request.POST.get('confirma_email')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirmar_senha = request.POST.get('confirmar_senha')
        cpf = request.POST.get('cpf')
        atuacao = request.POST.get('atuacao')
        cep = request.POST.get('cep')
        rua = request.POST.get('address')
        numero = request.POST.get('number')
        complemento = request.POST.get('complement')
        bairro = request.POST.get('neighborhood')
        cidade = request.POST.get('city')
        estado = request.POST.get('region')
        uestado = request.POST.get('uestado')
        instituicao = request.POST.get('universidades')
        grupo = get_object_or_404(Group, name='GrupoAluno')
        
        if (len(first_name.strip()) == 0) or (len(last_name.strip()) == 0) or (len(username.strip()) == 0) or\
                (len(email.strip()) == 0) or (len(senha.strip()) == 0) or (len(confirmar_senha.strip()) == 0):
            messages.add_message(request, constants.ERROR, 'Preencha todos os campos')
            return redirect('/cadastro_aluno')


        if not email_username(request, username, email):
            return redirect('/cadastro_aluno')

        if not password_is_valid(request, senha, confirmar_senha):
            return redirect('/cadastro_aluno')


        if not email_valido(request, email, User):
            return redirect('/cadastro_aluno')

        if not cpf_valido(request, cpf, Aluno):
            return redirect('/cadastro_empresa')

        try:

            try: estado = Estado.objects.get(estado=estado)

            except:
                estado = Estado(estado=estado)
                estado.save()

            try: cidade = Cidade.objects.get(cidade=cidade)
    
            except:
                cidade = Cidade(estado=estado, cidade=cidade)
                cidade.save()

            try: bairro = Bairro.objects.get(bairro=bairro)
                
            except:
                bairro = Bairro(cidade=cidade, bairro=bairro)
                bairro.save()

            try: cep = Endereco.objects.get(cep=cep)
            
            except:
                endereco = Endereco(bairro=bairro, rua=rua, cep=cep)
                endereco.save()

            try: complemento = Complemento.objects.get(complemento=complemento)
                
            except:
                complemento = Complemento(endereco = endereco, numero=numero, complemento=complemento)
                complemento.save()

            try: atuacao = Atuacao.objects.get(atuacao=atuacao)
            
            except:
                atuacao = Atuacao(atuacao = atuacao)
                atuacao.save()

            try: uestado = Estado.objects.get(estado=uestado)

            except:
                uestado = Estado(estado=uestado)
                uestado.save()

            try: instituicao = Universidades.objects.get(instituicao=instituicao)
            
            except:
                instituicao = Universidades(estado = estado, instituicao = instituicao)
                instituicao.save()
            
            user = User.objects.create_user(username=username,
                                            first_name=first_name,
                                            last_name=last_name,
                                            email=email,
                                            password=senha,
                                            is_active=True)
            user.groups.add(grupo)
            user.save()

            aluno = Aluno(cpf=cpf,
                    endereco=endereco,
                    atuacao=atuacao,
                    instituicao=instituicao,
                    usuario=user)
            aluno.save()
                        

            token = sha256(f'{first_name}{email}'.encode()).hexdigest()
            ativacao = Ativacao(token=token, user=user)
            ativacao.save()

            messages.add_message(request, constants.SUCCESS, 'Aluno cadastrado com SUCESSO! Faça LOGIN para continuar!')
            return redirect('login')

        except:
            messages.add_message(request, constants.ERROR, 'Erro interno no sistema!!!')
            return redirect('/cadastro_aluno')




def login(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('listar-projeto')
        return render(request, 'login.html')

    elif request.method == "POST":
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        user = auth.authenticate(username=email, password=senha)

        if not user:

autenticacao/templates/cadastro.html
{% extends "base.html" %}

{% load static %}

{% block title %}Ola Usuario{% endblock %}

{% block 'head' %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'autenticacao/css/css.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock %}

{% block 'main' %}

<div class="col-md-12">
    <div class="row">

        <div class="col-md-3 sidebar">
            <div class="logo_sidebar">
                <h2 class="logo">
                    <a href="{% url 'pages:home' %}">
                        <img class="img_logo_sidebar" src="{% static 'autenticacao/img/logo_nutri_lab.png' %}">
                    </a>
                </h2>
            </div>
        </div>

        <div class="margem col-md-6">      
            <h2 class="textcenter">Conta para Aluno</h2>
            
            <table>
                <td><img class="alunogif" src="{% static 'autenticacao/img/aluno.gif' %}"></td>
                <td><p class="lead">Com usuario aluno você pode selecionar um projeto e contatar uma empresa.</p>
                   
                </td>
            </table>
               <div class="d-grid gap-2 d-md-flex justify-content-md-center">    
                        <a href="{% url 'cadastro_aluno' %}" class="btn btn-outline-secondary btn-lg">Cadastrar Aluno</a>        
                    </div>    
                    
                 

            <h2 class="textcenter">Conta para Empresa</h2>

            <table>
                <td><img class="empresagif" src="{% static 'autenticacao/img/empresa.gif' %}"></td>
                <td><p class="lead">Com usuario empresa você pode postar varios <br> projeto e contatar até 3 alunos para desencolver cada projeto.</p>     
                
                </td>
                
            </table>       
                    
            <div class="d-grid gap-2 d-md-flex justify-content-md-center">      
                <a href="{% url 'cadastro_empresa' %}" class="btn btn-outline-secondary btn-lg">Cadastrar Empresa</a>
            </div>     
        </div>

        <div class="col-3 sidebar">
            <div class="logo_sidebar">
                <h2 class="logo">

                </h2>
            </div>
        </div>

       
    </div>
</div>


{% endblock %}

autenticacao/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block 'head' %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'autenticacao/css/css.css' %}">
{% endblock %}

{% block title %}Login{% endblock %}

{% block 'main' %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 sidebar">
            <div class="logo_sidebar">
                <h2 class="logo"><a href="{% url 'pages:home' %}"><img class="img_logo_sidebar" src="{% static 'autenticacao/img/logo_nutri_lab.png' %}"></a>
                </h2>
                <h2 class="logo">
                    <img class="img_logo_sidebar" src="{% static 'autenticacao/img/fundo_background.png' %}">
                </h2>
            </div>
        </div>
        <div class="col-md-9">
            <div class="area_cadastrar">
                <h4 style="bottom: 30px; font-weight: bold">Não tem uma conta ?&nbsp <a href="{% url 'cadastro' %}"
                        class="btn btn-outline-secondary btn-lg">Registre-se</a></h4><br>
                {% if messages %}
                <br>
                {% for message in messages %}
                <div class="alert {{message.tags}}">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}
                <h2 class="titulo">Bem vindo novamente</h2>
                <p class="sub-titulo">Entre com sua conta</p>
                <hr>
                <form action="{% url 'login'%}" method="POST">{% csrf_token %}
                    <span class="bold">E-mail</span>
                    <input class="form-control input-form col-md-6" name="email" type="text" placeholder="Digite seu E-mail...">
                    <br>
                    <span class="bold">Senha</span>
                    <input class="form-control input-form col-md-4" name="senha" type="password"
                           placeholder="Digite sua senha...">
                    <br>
                    <button type="submit" class="btn-first">Entrar</button>
                </form>
            </div>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}