api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('api/cadastro/empresa', CadastroEmpresaApi.as_view())
]

paginas/urls.py
from django.urls import path
from .views import PaginaInicial, Sobre

app_name = "pages"

urlpatterns = [
    # path('endereço/', MinhaView.as_view(), name='nome da url'),
    path('', PaginaInicial.as_view(), name='home'),
    path('sobre/', Sobre.as_view(), name='sobre'),
    ]

sintproedu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('autenticacao.urls')),
    path('', include ('paginas.urls')),
    path('', include ('core.urls')),
    path('', include ('api.urls')),
]

paginas/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class PaginaInicial(TemplateView):
    template_name = 'paginas/home.html'


class Sobre(TemplateView):
    template_name = 'paginas/sobre.html'

paginas/templates/paginas/home.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}Pagina inicial{% endblock %}

{% block 'head2' %}
    <link rel="stylesheet" href="{% static 'css/slide.css' %}">
{% endblock %}

{% block content %}
<div class="container-fluid">
        <div class="slider">
            <div class="slides">
                <input type="radio" name="radio-btn" id="radio1">
                <input type="radio" name="radio-btn" id="radio2">
                <input type="radio" name="radio-btn" id="radio3">
                <input type="radio" name="radio-btn" id="radio4">

                <div class="slide first">
                    <img src="{% static '/img/img01.jpg'%}" alt="">
                </div>

                <div class="slide">
                    <img src="{% static '/img/img2.jpg'%}" alt="">
                </div>

                <div class="slide">
                    <img src="{% static '/img/img3.jpg'%}" alt="">
                </div>

                <div class="slide">
                    <img src="{% static '/img/img4.jpg'%}" alt="">
                </div>

                <div class="navigation-auto">
                    <div class="auto-btn1"></div>
                    <div class="auto-btn2"></div>
                    <div class="auto-btn3"></div>
                    <div class="auto-btn4"></div>
                </div>
            </div>

            <div>
                <div class="manual-navigation">
                    <label for="radio1" class="manual-btn"></label>
                    <label for="radio2" class="manual-btn"></label>
                    <label for="radio3" class="manual-btn"></label>
                    <label for="radio4" class="manual-btn"></label>
                </div>
            </div>
        </div>


    <div class="row div-button btn-group btn-group-toggle">
        <a class="nav-link button-link" href="{% url 'login' %}">Login</a>
        <a class="nav-link button-link" href="{% url 'cadastro' %}">Cadastro</a>
        <a class="nav-link button-link" href="{% url 'pages:sobre' %}">Saiba Mais</a>
    </div>

</div>

<script src= "{% static '/js/slider.js' %}"></script>
<style>
    body {
        background-image: url("{% static 'img/fundo01.jpg' %}"); /* Substitua pelo caminho da sua imagem */
        background-size: cover; /* Ajusta a imagem para cobrir toda a página */
        background-repeat: no-repeat; /* Impede que a imagem se repita */
        background-attachment: fixed; /* Fixa o fundo ao rolar a página */
    }
</style>

{% endblock %}

{% block 'footer' %}
<footer>
    <p class="text-center">Unindo alunos e empresas para soluções reais</p>  <!-- Centraliza o texto do footer -->
</footer>
{% endblock %}

paginas/templates/paginas/sobre.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}Sobre SintProEdu{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            <h3>SintProEdu</h3>  <!-- Centraliza o título -->
            <hr>
        </div>
    </div>

    <!-- Primeira seção com texto e imagem centralizados -->
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h5>Quem Somos?</h5>  <!-- Centraliza o título --><br>
            <p>
                SintProEdu foi criada com o objetivo facilitar a comunicação entre alunos e empresas na elaboração de
                projetos acadêmicos a fim de resolver possíveis problemas que esta venha a ter.<br>
                Durante nossa pesquisa percebemos a grande dificuldade em conseguir falar com as pessoas
                responsáveis pelas empresas. <br>A Sintproedu é uma plataforma faz a ponte entre alunos e empresas.
                Em nosso banco de dados estão armazenados os cadastros de empresas interessadas em resolver algum
                problema tecnológico e de alunos dispostos a criar uma solução. Bem como a descrição desses projetos que
                estão em andamento.
            </p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/img4.jpg' %}" class="img-fluid d-block mx-auto" alt="Descrição da imagem">  <!-- Centraliza a imagem -->
        </div>
    </div>
<div class="col-md-10 mx-auto">
    <br><hr><br>
</div>
    <!-- Segunda seção com imagem à esquerda e texto à direita, ambos centralizados -->
    <div class="row justify-content-center">
        <div class="col-md-5">
            <img src="{% static 'img/img3.jpg' %}" class="img-fluid d-block mx-auto" alt="Descrição da imagem">  <!-- Centraliza a imagem -->
        </div>
        <div class="col-md-5">
            <h5>Por que?</h5>  <!-- Centraliza o título --><br>
            <p>
                Todo aluno em algum estágio de sua formação universitária precisa elaborar algum tipo de
                projeto que vise colocar em prática as teorias estudadas em sala de aula,
                porém nem sempre isso é uma tarefa fácil, principalmente no momento em que nosso
                planeta vem passando. Devido ao distanciamento social, o contato com a comunidade externa
                foi muito comprometida e o acesso dos estudantes aos ambientes das empresas ficou ainda mais
                complicado. Pensando nessas dificuldades, a Sintproedu tornou menos complicado o acesso dos
                alunos às necessidades do mercado.
                Contribuindo para a formação dos estudantes que poderão colocar em prática as teorias
                estudadas, quanto para as empresas que terão ajuda na resolução de seus problemas.
            </p>
        </div>
    </div>

    <br><br><br>

    <div class="row">
        <div class="col-md-10 mx-auto">
            <h4>Cláusulas de exclusão de responsabilidade</h4>  <!-- Centraliza o título -->
            <hr>
        </div>
    </div>

    <!-- Última seção com texto e imagem -->
    <div class="row justify-content-center">
        <div class="col-md-5">
            <p>
                A Sintproedu é uma projeto didático apresentado à Univesp (Universidade Virtual do Estado de São Paulo).
                Na disciplina de Projeto Integrador, com a finalidade de facilitar a integração dos estudantes com
                empresas interessadas na parceria entre ambas. (aluno/empresas).<br>Por se tratar de um trabalho
                acadêmico sem fins comerciais, a Sintproedu, não se responsabiliza pelas informações fornecidas nessa
                plataforma pelos seus usuários, nem com os possíveis projetos realizados e a veracidade das informações
                fornecidas pelas partes envolvidas.<br>Por se tratar de um projeto experimental, não garantimos que
                todas as funcionalidades do site funcionem corretamente, podendo haver algumas falhas, erros ou perdas
                de dados. <br>A Sintproedu não fará intermediações no contato entre empresa e alunos ou instituições,
                os contatos serão feitos diretamente entre as partes interessadas, sem nenhuma interferência ou suporte
                da nossa parte. Nos limitamos unicamente a disponibilizar a plataforma para interação entre as partes.<br>
                A Sintproedu não cobrará nenhum valor pela utilização da plataforma nem autoriza ninguém a receber ou
                efetuar pagamento em nome da mesma.<br>Todas as informações fornecidas pelos usuários e ou empresa são
                de responsabilidade das partes envolvidas. <br>O utilizador do site que aceitar fazer uso da plataforma
                aceita os termos deste contrato descritos nos parágrafos acima.<br>
            </p>
        </div>
        <div class="col-md-5">
            <img src="{% static 'img/img01.jpg' %}" class="img-fluid d-block mx-auto" alt="Descrição da imagem">  <!-- Centraliza a imagem -->
        </div>
    </div>
</div>
<br>

{% endblock %}

{% block 'footer' %}
<footer>
    <p class="text-center">Unindo alunos e empresas para soluções reais</p>  <!-- Centraliza o texto do footer -->
</footer>
{% endblock %}